// Generated by gencpp from file wa_two/Belief.msg
// DO NOT EDIT!


#ifndef WA_TWO_MESSAGE_BELIEF_H
#define WA_TWO_MESSAGE_BELIEF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wa_two
{
template <class ContainerAllocator>
struct Belief_
{
  typedef Belief_<ContainerAllocator> Type;

  Belief_()
    : info_vector()
    , info_matrix()  {
    }
  Belief_(const ContainerAllocator& _alloc)
    : info_vector(_alloc)
    , info_matrix(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _info_vector_type;
  _info_vector_type info_vector;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _info_matrix_type;
  _info_matrix_type info_matrix;





  typedef boost::shared_ptr< ::wa_two::Belief_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wa_two::Belief_<ContainerAllocator> const> ConstPtr;

}; // struct Belief_

typedef ::wa_two::Belief_<std::allocator<void> > Belief;

typedef boost::shared_ptr< ::wa_two::Belief > BeliefPtr;
typedef boost::shared_ptr< ::wa_two::Belief const> BeliefConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wa_two::Belief_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wa_two::Belief_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wa_two

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wa_two': ['/home/sdhoro/amr/AMR-workshops/src/wa_two/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wa_two::Belief_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wa_two::Belief_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wa_two::Belief_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wa_two::Belief_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wa_two::Belief_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wa_two::Belief_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wa_two::Belief_<ContainerAllocator> >
{
  static const char* value()
  {
    return "496b863397b7d14fe88da289c2e89a57";
  }

  static const char* value(const ::wa_two::Belief_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x496b863397b7d14fULL;
  static const uint64_t static_value2 = 0xe88da289c2e89a57ULL;
};

template<class ContainerAllocator>
struct DataType< ::wa_two::Belief_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wa_two/Belief";
  }

  static const char* value(const ::wa_two::Belief_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wa_two::Belief_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] info_vector\n\
float64[] info_matrix\n\
";
  }

  static const char* value(const ::wa_two::Belief_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wa_two::Belief_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info_vector);
      stream.next(m.info_matrix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Belief_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wa_two::Belief_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wa_two::Belief_<ContainerAllocator>& v)
  {
    s << indent << "info_vector[]" << std::endl;
    for (size_t i = 0; i < v.info_vector.size(); ++i)
    {
      s << indent << "  info_vector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.info_vector[i]);
    }
    s << indent << "info_matrix[]" << std::endl;
    for (size_t i = 0; i < v.info_matrix.size(); ++i)
    {
      s << indent << "  info_matrix[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.info_matrix[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WA_TWO_MESSAGE_BELIEF_H
