// Generated by gencpp from file perception/Landmark.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_LANDMARK_H
#define PERCEPTION_MESSAGE_LANDMARK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace perception
{
template <class ContainerAllocator>
struct Landmark_
{
  typedef Landmark_<ContainerAllocator> Type;

  Landmark_()
    : pos()
    , signature(0)  {
    }
  Landmark_(const ContainerAllocator& _alloc)
    : pos(_alloc)
    , signature(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_type;
  _pos_type pos;

   typedef int32_t _signature_type;
  _signature_type signature;





  typedef boost::shared_ptr< ::perception::Landmark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::Landmark_<ContainerAllocator> const> ConstPtr;

}; // struct Landmark_

typedef ::perception::Landmark_<std::allocator<void> > Landmark;

typedef boost::shared_ptr< ::perception::Landmark > LandmarkPtr;
typedef boost::shared_ptr< ::perception::Landmark const> LandmarkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::Landmark_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::Landmark_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'perception': ['/home/sdhoro/amr/AMR-workshops/src/perception/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception::Landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Landmark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Landmark_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e6d3e1d7cb152c50ed2022872aedb5a";
  }

  static const char* value(const ::perception::Landmark_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e6d3e1d7cb152c5ULL;
  static const uint64_t static_value2 = 0x0ed2022872aedb5aULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/Landmark";
  }

  static const char* value(const ::perception::Landmark_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point pos\n\
int32 signature\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::perception::Landmark_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::Landmark_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
      stream.next(m.signature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Landmark_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::Landmark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::Landmark_<ContainerAllocator>& v)
  {
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
    s << indent << "signature: ";
    Printer<int32_t>::stream(s, indent + "  ", v.signature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_LANDMARK_H
