// Generated by gencpp from file perception/Landmarks.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_LANDMARKS_H
#define PERCEPTION_MESSAGE_LANDMARKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <perception/Landmark.h>

namespace perception
{
template <class ContainerAllocator>
struct Landmarks_
{
  typedef Landmarks_<ContainerAllocator> Type;

  Landmarks_()
    : landmarks()  {
    }
  Landmarks_(const ContainerAllocator& _alloc)
    : landmarks(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::perception::Landmark_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception::Landmark_<ContainerAllocator> >::other >  _landmarks_type;
  _landmarks_type landmarks;





  typedef boost::shared_ptr< ::perception::Landmarks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::Landmarks_<ContainerAllocator> const> ConstPtr;

}; // struct Landmarks_

typedef ::perception::Landmarks_<std::allocator<void> > Landmarks;

typedef boost::shared_ptr< ::perception::Landmarks > LandmarksPtr;
typedef boost::shared_ptr< ::perception::Landmarks const> LandmarksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::Landmarks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::Landmarks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'perception': ['/home/sdhoro/amr/AMR-workshops/src/perception/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception::Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Landmarks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Landmarks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Landmarks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Landmarks_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05a8c6fbb4d17bf98d97c22d108642e6";
  }

  static const char* value(const ::perception::Landmarks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05a8c6fbb4d17bf9ULL;
  static const uint64_t static_value2 = 0x8d97c22d108642e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/Landmarks";
  }

  static const char* value(const ::perception::Landmarks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Landmark[] landmarks\n\
\n\
================================================================================\n\
MSG: perception/Landmark\n\
geometry_msgs/Point pos\n\
int32 signature\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::perception::Landmarks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::Landmarks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.landmarks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Landmarks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::Landmarks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::Landmarks_<ContainerAllocator>& v)
  {
    s << indent << "landmarks[]" << std::endl;
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      s << indent << "  landmarks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception::Landmark_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_LANDMARKS_H
