// Generated by gencpp from file perception/Observation.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_OBSERVATION_H
#define PERCEPTION_MESSAGE_OBSERVATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception
{
template <class ContainerAllocator>
struct Observation_
{
  typedef Observation_<ContainerAllocator> Type;

  Observation_()
    : range(0.0)
    , bearing(0.0)
    , signature(0.0)  {
    }
  Observation_(const ContainerAllocator& _alloc)
    : range(0.0)
    , bearing(0.0)
    , signature(0.0)  {
  (void)_alloc;
    }



   typedef float _range_type;
  _range_type range;

   typedef float _bearing_type;
  _bearing_type bearing;

   typedef float _signature_type;
  _signature_type signature;





  typedef boost::shared_ptr< ::perception::Observation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::Observation_<ContainerAllocator> const> ConstPtr;

}; // struct Observation_

typedef ::perception::Observation_<std::allocator<void> > Observation;

typedef boost::shared_ptr< ::perception::Observation > ObservationPtr;
typedef boost::shared_ptr< ::perception::Observation const> ObservationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::Observation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::Observation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'perception': ['/home/sdhoro/amr/AMR-workshops/src/perception/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception::Observation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Observation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Observation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Observation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Observation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Observation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::Observation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "072e563d2457492566310b362a4d08be";
  }

  static const char* value(const ::perception::Observation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x072e563d24574925ULL;
  static const uint64_t static_value2 = 0x66310b362a4d08beULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::Observation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/Observation";
  }

  static const char* value(const ::perception::Observation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::Observation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 range\n\
float32 bearing\n\
float32 signature\n\
";
  }

  static const char* value(const ::perception::Observation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::Observation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.range);
      stream.next(m.bearing);
      stream.next(m.signature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Observation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::Observation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::Observation_<ContainerAllocator>& v)
  {
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "bearing: ";
    Printer<float>::stream(s, indent + "  ", v.bearing);
    s << indent << "signature: ";
    Printer<float>::stream(s, indent + "  ", v.signature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_OBSERVATION_H
