// Generated by gencpp from file perception/Observations.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_OBSERVATIONS_H
#define PERCEPTION_MESSAGE_OBSERVATIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <perception/Observation.h>

namespace perception
{
template <class ContainerAllocator>
struct Observations_
{
  typedef Observations_<ContainerAllocator> Type;

  Observations_()
    : observations()  {
    }
  Observations_(const ContainerAllocator& _alloc)
    : observations(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::perception::Observation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception::Observation_<ContainerAllocator> >::other >  _observations_type;
  _observations_type observations;





  typedef boost::shared_ptr< ::perception::Observations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::Observations_<ContainerAllocator> const> ConstPtr;

}; // struct Observations_

typedef ::perception::Observations_<std::allocator<void> > Observations;

typedef boost::shared_ptr< ::perception::Observations > ObservationsPtr;
typedef boost::shared_ptr< ::perception::Observations const> ObservationsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::Observations_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::Observations_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'perception': ['/home/sdhoro/amr/AMR-workshops/src/perception/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception::Observations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Observations_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Observations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Observations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Observations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Observations_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::Observations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83718f2217d5edf089e92c5bcad51532";
  }

  static const char* value(const ::perception::Observations_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83718f2217d5edf0ULL;
  static const uint64_t static_value2 = 0x89e92c5bcad51532ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::Observations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/Observations";
  }

  static const char* value(const ::perception::Observations_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::Observations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Observation[] observations\n\
\n\
================================================================================\n\
MSG: perception/Observation\n\
float32 range\n\
float32 bearing\n\
float32 signature\n\
";
  }

  static const char* value(const ::perception::Observations_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::Observations_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.observations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Observations_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::Observations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::Observations_<ContainerAllocator>& v)
  {
    s << indent << "observations[]" << std::endl;
    for (size_t i = 0; i < v.observations.size(); ++i)
    {
      s << indent << "  observations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception::Observation_<ContainerAllocator> >::stream(s, indent + "    ", v.observations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_OBSERVATIONS_H
